# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from obj_detected/pred_draw.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import obj_detected.msg
import sensor_msgs.msg
import std_msgs.msg

class pred_draw(genpy.Message):
  _md5sum = "6b672082de2bd40ed37d92cb6b8fa3d7"
  _type = "obj_detected/pred_draw"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """sensor_msgs/Image cur_color_img
ball_pose cur_ball_pose
================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of camera
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: obj_detected/ball_pose
# 从图像输出的小球三维坐标
float64 x
float64 y
float64 z
float32 T   #周期
int8 count  #第几组数据，不一定用

#但是定义好之后不能直接使用，需要进行编译
"""
  __slots__ = ['cur_color_img','cur_ball_pose']
  _slot_types = ['sensor_msgs/Image','obj_detected/ball_pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cur_color_img,cur_ball_pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pred_draw, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cur_color_img is None:
        self.cur_color_img = sensor_msgs.msg.Image()
      if self.cur_ball_pose is None:
        self.cur_ball_pose = obj_detected.msg.ball_pose()
    else:
      self.cur_color_img = sensor_msgs.msg.Image()
      self.cur_ball_pose = obj_detected.msg.ball_pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.cur_color_img.header.seq, _x.cur_color_img.header.stamp.secs, _x.cur_color_img.header.stamp.nsecs))
      _x = self.cur_color_img.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cur_color_img.height, _x.cur_color_img.width))
      _x = self.cur_color_img.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.cur_color_img.is_bigendian, _x.cur_color_img.step))
      _x = self.cur_color_img.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3dfb().pack(_x.cur_ball_pose.x, _x.cur_ball_pose.y, _x.cur_ball_pose.z, _x.cur_ball_pose.T, _x.cur_ball_pose.count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cur_color_img is None:
        self.cur_color_img = sensor_msgs.msg.Image()
      if self.cur_ball_pose is None:
        self.cur_ball_pose = obj_detected.msg.ball_pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.cur_color_img.header.seq, _x.cur_color_img.header.stamp.secs, _x.cur_color_img.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cur_color_img.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cur_color_img.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cur_color_img.height, _x.cur_color_img.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cur_color_img.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cur_color_img.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.cur_color_img.is_bigendian, _x.cur_color_img.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cur_color_img.data = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.cur_ball_pose.x, _x.cur_ball_pose.y, _x.cur_ball_pose.z, _x.cur_ball_pose.T, _x.cur_ball_pose.count,) = _get_struct_3dfb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.cur_color_img.header.seq, _x.cur_color_img.header.stamp.secs, _x.cur_color_img.header.stamp.nsecs))
      _x = self.cur_color_img.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.cur_color_img.height, _x.cur_color_img.width))
      _x = self.cur_color_img.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.cur_color_img.is_bigendian, _x.cur_color_img.step))
      _x = self.cur_color_img.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3dfb().pack(_x.cur_ball_pose.x, _x.cur_ball_pose.y, _x.cur_ball_pose.z, _x.cur_ball_pose.T, _x.cur_ball_pose.count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cur_color_img is None:
        self.cur_color_img = sensor_msgs.msg.Image()
      if self.cur_ball_pose is None:
        self.cur_ball_pose = obj_detected.msg.ball_pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.cur_color_img.header.seq, _x.cur_color_img.header.stamp.secs, _x.cur_color_img.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cur_color_img.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cur_color_img.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.cur_color_img.height, _x.cur_color_img.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cur_color_img.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cur_color_img.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.cur_color_img.is_bigendian, _x.cur_color_img.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.cur_color_img.data = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.cur_ball_pose.x, _x.cur_ball_pose.y, _x.cur_ball_pose.z, _x.cur_ball_pose.T, _x.cur_ball_pose.count,) = _get_struct_3dfb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3dfb = None
def _get_struct_3dfb():
    global _struct_3dfb
    if _struct_3dfb is None:
        _struct_3dfb = struct.Struct("<3dfb")
    return _struct_3dfb
_struct_BI = None
def _get_struct_BI():
    global _struct_BI
    if _struct_BI is None:
        _struct_BI = struct.Struct("<BI")
    return _struct_BI
