// Generated by gencpp from file learning_ros_gyh21/Person_srvRequest.msg
// DO NOT EDIT!


#ifndef LEARNING_ROS_GYH21_MESSAGE_PERSON_SRVREQUEST_H
#define LEARNING_ROS_GYH21_MESSAGE_PERSON_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_ros_gyh21
{
template <class ContainerAllocator>
struct Person_srvRequest_
{
  typedef Person_srvRequest_<ContainerAllocator> Type;

  Person_srvRequest_()
    : name()
    , age(0)
    , sex(0)  {
    }
  Person_srvRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , sex(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _age_type;
  _age_type age;

   typedef uint8_t _sex_type;
  _sex_type sex;



  enum {
    unknown = 0u,
    male = 1u,
    female = 2u,
  };


  typedef boost::shared_ptr< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Person_srvRequest_

typedef ::learning_ros_gyh21::Person_srvRequest_<std::allocator<void> > Person_srvRequest;

typedef boost::shared_ptr< ::learning_ros_gyh21::Person_srvRequest > Person_srvRequestPtr;
typedef boost::shared_ptr< ::learning_ros_gyh21::Person_srvRequest const> Person_srvRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace learning_ros_gyh21

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'learning_ros_gyh21': ['/home/free/catkin_kinect2/src/learning_ros_gyh21/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3f7ec37d11629ec3010e27635cf22a9";
  }

  static const char* value(const ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3f7ec37d11629ecULL;
  static const uint64_t static_value2 = 0x3010e27635cf22a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_ros_gyh21/Person_srvRequest";
  }

  static const char* value(const ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
uint8 age\n\
uint8 sex\n\
\n\
uint8 unknown = 0\n\
uint8 male = 1\n\
uint8 female = 2\n\
";
  }

  static const char* value(const ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.sex);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_ros_gyh21::Person_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "sex: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sex);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_ROS_GYH21_MESSAGE_PERSON_SRVREQUEST_H
