// Generated by gencpp from file learning_ros_gyh21/Person_srv.msg
// DO NOT EDIT!


#ifndef LEARNING_ROS_GYH21_MESSAGE_PERSON_SRV_H
#define LEARNING_ROS_GYH21_MESSAGE_PERSON_SRV_H

#include <ros/service_traits.h>


#include <learning_ros_gyh21/Person_srvRequest.h>
#include <learning_ros_gyh21/Person_srvResponse.h>


namespace learning_ros_gyh21
{

struct Person_srv
{

typedef Person_srvRequest Request;
typedef Person_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Person_srv
} // namespace learning_ros_gyh21


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_ros_gyh21::Person_srv > {
  static const char* value()
  {
    return "c198113e7dd9cc5c9fd5f271c8479b39";
  }

  static const char* value(const ::learning_ros_gyh21::Person_srv&) { return value(); }
};

template<>
struct DataType< ::learning_ros_gyh21::Person_srv > {
  static const char* value()
  {
    return "learning_ros_gyh21/Person_srv";
  }

  static const char* value(const ::learning_ros_gyh21::Person_srv&) { return value(); }
};


// service_traits::MD5Sum< ::learning_ros_gyh21::Person_srvRequest> should match 
// service_traits::MD5Sum< ::learning_ros_gyh21::Person_srv > 
template<>
struct MD5Sum< ::learning_ros_gyh21::Person_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_ros_gyh21::Person_srv >::value();
  }
  static const char* value(const ::learning_ros_gyh21::Person_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_ros_gyh21::Person_srvRequest> should match 
// service_traits::DataType< ::learning_ros_gyh21::Person_srv > 
template<>
struct DataType< ::learning_ros_gyh21::Person_srvRequest>
{
  static const char* value()
  {
    return DataType< ::learning_ros_gyh21::Person_srv >::value();
  }
  static const char* value(const ::learning_ros_gyh21::Person_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_ros_gyh21::Person_srvResponse> should match 
// service_traits::MD5Sum< ::learning_ros_gyh21::Person_srv > 
template<>
struct MD5Sum< ::learning_ros_gyh21::Person_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_ros_gyh21::Person_srv >::value();
  }
  static const char* value(const ::learning_ros_gyh21::Person_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_ros_gyh21::Person_srvResponse> should match 
// service_traits::DataType< ::learning_ros_gyh21::Person_srv > 
template<>
struct DataType< ::learning_ros_gyh21::Person_srvResponse>
{
  static const char* value()
  {
    return DataType< ::learning_ros_gyh21::Person_srv >::value();
  }
  static const char* value(const ::learning_ros_gyh21::Person_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_ROS_GYH21_MESSAGE_PERSON_SRV_H
