// Generated by gencpp from file learning_ros_gyh21/Person_srvResponse.msg
// DO NOT EDIT!


#ifndef LEARNING_ROS_GYH21_MESSAGE_PERSON_SRVRESPONSE_H
#define LEARNING_ROS_GYH21_MESSAGE_PERSON_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_ros_gyh21
{
template <class ContainerAllocator>
struct Person_srvResponse_
{
  typedef Person_srvResponse_<ContainerAllocator> Type;

  Person_srvResponse_()
    : result()  {
    }
  Person_srvResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Person_srvResponse_

typedef ::learning_ros_gyh21::Person_srvResponse_<std::allocator<void> > Person_srvResponse;

typedef boost::shared_ptr< ::learning_ros_gyh21::Person_srvResponse > Person_srvResponsePtr;
typedef boost::shared_ptr< ::learning_ros_gyh21::Person_srvResponse const> Person_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace learning_ros_gyh21

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'learning_ros_gyh21': ['/home/free/catkin_kinect2/src/learning_ros_gyh21/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_ros_gyh21/Person_srvResponse";
  }

  static const char* value(const ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n\
";
  }

  static const char* value(const ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_ros_gyh21::Person_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_ROS_GYH21_MESSAGE_PERSON_SRVRESPONSE_H
